# Generated by Django 3.2 on 2024-11-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='f_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_contraseña',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino'], [2, 'Otro']]),
        ),
    ]
