# Generated by Django 3.2 on 2024-11-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20241125_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan_contratar',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
