# Generated by Django 3.2 on 2024-11-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20241125_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
